stages:
 - test
 - build
 - deploy

test:
  stage: test
  image: node:10
  before_script:
    - npm ci
  script: npm run test

build:
  stage: build
  image: node:10
  before_script:
    - npm ci
  script: npm run build
  artifacts:
    paths:
      - dist/

deploy-to-s3:
 stage: deploy
 image: garland/aws-cli-docker
 script: ./deploy-to-s3.sh myS3bucket
 only:
  - master
